import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const pipelineScript = join(projectRoot, "scripts", "scheduled-memory-pipeline.sh");
const pipelineRecipe = join(projectRoot, "docs", "recipes", "scheduled-memory-pipeline.md");

async function runPipeline(reviewOutput, options = {}) {
  const sandbox = await mkdtemp(join(tmpdir(), "marrow-scheduled-pipeline-"));
  const binDir = join(sandbox, "bin");
  const commandLog = join(sandbox, "commands.log");
  const fakeNode = join(binDir, "node");
  await mkdir(binDir, { recursive: true });
  await writeFile(
    fakeNode,
    `#!/usr/bin/env bash
set -euo pipefail
if [[ "\${1:-}" == "-e" ]]; then
  exec "$REAL_NODE" "$@"
fi
shift
printf '%s\\n' "$*" >> "$COMMAND_LOG"
if [[ "\${1:-} \${2:-}" == "quality review-learnings" ]]; then
  printf '%s\\n' "$MOCK_REVIEW_OUTPUT"
  exit "${options.reviewExitCode ?? 0}"
fi
printf '{}\\n'
`,
    "utf8",
  );
  await chmod(fakeNode, 0o755);

  const result = spawnSync("bash", [pipelineScript], {
    cwd: projectRoot,
    encoding: "utf8",
    env: {
      ...process.env,
      MARROW_ROOT: join(sandbox, "runtime"),
      COMMAND_LOG: commandLog,
      MOCK_REVIEW_OUTPUT: JSON.stringify(reviewOutput),
      OPENROUTER_API_KEY: options.apiKey === false ? "" : "test-key",
      ASD_ENABLE_COMPACTION: options.compaction ? "1" : "0",
      PATH: `${binDir}:${process.env.PATH}`,
      REAL_NODE: process.execPath,
    },
  });
  const commands = await readFile(commandLog, "utf8").catch(() => "");
  await rm(sandbox, { force: true, recursive: true });
  return { commands, result };
}

test("scheduled pipeline applies the exact batch generated by its review run", async () => {
  const batchPath = "/tmp/runtime/reports/llm-learning-review-batches/run-123.json";
  const { commands, result } = await runPipeline({
    generated_batch: true,
    batch_id: `sha256:${"a".repeat(64)}`,
    batch_path: batchPath,
  });

  assert.equal(result.status, 0, result.stderr);
  assert.match(commands, /quality review-learnings/);
  assert.ok(commands.includes(`quality apply-learning-review --batch ${batchPath}`));
  assert.doesNotMatch(commands, /quality apply-learning-review\s*$/m);
});

test("scheduled pipeline compacts only after a successful generated review batch when opted in", async () => {
  const { commands, result } = await runPipeline(
    {
      generated_batch: true,
      batch_id: `sha256:${"a".repeat(64)}`,
      batch_path: "/tmp/runtime/reports/llm-learning-review-batches/run-456.json",
    },
    { compaction: true },
  );

  assert.equal(result.status, 0, result.stderr);
  assert.match(
    commands,
    /storage cleanup-parsed --apply --older-than-days 30 --max-total-bytes 1073741824/,
  );
  assert.match(commands, /storage retain-reports --apply --older-than-days 30/);
});

test("scheduled pipeline cleans parsed storage when review generates no batch", async () => {
  const { commands, result } = await runPipeline({
    generated_batch: false,
    batch_id: null,
    batch_path: null,
    skipped: true,
    skip_reason: "llm_usd_budget_exhausted",
  });

  assert.equal(result.status, 0, result.stderr);
  assert.match(commands, /quality review-learnings/);
  assert.doesNotMatch(commands, /quality apply-learning-review/);
  assert.match(result.stdout, /no batch generated; skipping apply-learning-review/);
  assert.match(
    commands,
    /storage cleanup-parsed --apply --older-than-days 30 --max-total-bytes 1073741824/,
  );
  assert.doesNotMatch(commands, /storage retain-reports/);
});

test("scheduled pipeline cleans parsed storage before stopping on review failure", async () => {
  const { commands, result } = await runPipeline(
    {
      generated_batch: true,
      batch_path: "/tmp/stale-batch.json",
    },
    { reviewExitCode: 17 },
  );

  assert.equal(result.status, 17);
  assert.match(commands, /storage cleanup-parsed --apply/);
  assert.match(commands, /quality review-learnings/);
  assert.doesNotMatch(commands, /quality apply-learning-review/);
  assert.doesNotMatch(commands, /storage retain-reports/);
});

test("scheduled pipeline skips review but still retains parsed staging without credentials", async () => {
  const { commands, result } = await runPipeline({}, { apiKey: false });

  assert.equal(result.status, 0, result.stderr);
  assert.doesNotMatch(commands, /quality review-learnings/);
  assert.doesNotMatch(commands, /quality apply-learning-review/);
  assert.match(commands, /storage cleanup-parsed --apply/);
});

test("scheduled cleanup runs before audit and docs describe receipt retries and environment", async () => {
  const { commands, result } = await runPipeline({ generated_batch: false });
  assert.equal(result.status, 0, result.stderr);
  const lines = commands.trim().split("\n");
  const cleanupIndex = lines.findIndex((line) => line.startsWith("storage cleanup-parsed --apply"));
  const auditIndex = lines.findIndex((line) => line.startsWith("quality audit"));
  const reviewIndex = lines.findIndex((line) => line.startsWith("quality review-learnings"));
  assert.ok(cleanupIndex >= 0 && cleanupIndex < auditIndex && auditIndex < reviewIndex);

  const recipe = await readFile(pipelineRecipe, "utf8");
  assert.match(
    recipe,
    /pipeline gate --skip-ingest[\s\S]*storage cleanup-parsed --apply[\s\S]*quality audit/,
  );
  assert.match(recipe, /failed or interrupted applying receipts are retried immediately/i);
  assert.match(recipe, /`ASD_PARSED_RETENTION_OLDER_THAN_DAYS`/);
  assert.match(recipe, /`ASD_PARSED_MAX_TOTAL_BYTES`/);
});
