import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const pipelineScript = join(projectRoot, "scripts", "scheduled-memory-pipeline.sh");

async function runPipeline(reviewOutput, options = {}) {
  const sandbox = await mkdtemp(join(tmpdir(), "asd-scheduled-pipeline-"));
  const binDir = join(sandbox, "bin");
  const commandLog = join(sandbox, "commands.log");
  const fakeNode = join(binDir, "node");
  await mkdir(binDir, { recursive: true });
  await writeFile(
    fakeNode,
    `#!/usr/bin/env bash
set -euo pipefail
if [[ "\${1:-}" == "-e" ]]; then
  exec "$REAL_NODE" "$@"
fi
shift
printf '%s\\n' "$*" >> "$COMMAND_LOG"
if [[ "\${1:-} \${2:-}" == "quality review-learnings" ]]; then
  printf '%s\\n' "$MOCK_REVIEW_OUTPUT"
  exit "${options.reviewExitCode ?? 0}"
fi
printf '{}\\n'
`,
    "utf8",
  );
  await chmod(fakeNode, 0o755);

  const result = spawnSync("bash", [pipelineScript], {
    cwd: projectRoot,
    encoding: "utf8",
    env: {
      ...process.env,
      AGENT_SESSION_DISTILLERY_ROOT: join(sandbox, "runtime"),
      COMMAND_LOG: commandLog,
      MOCK_REVIEW_OUTPUT: JSON.stringify(reviewOutput),
      OPENROUTER_API_KEY: options.apiKey === false ? "" : "test-key",
      PATH: `${binDir}:${process.env.PATH}`,
      REAL_NODE: process.execPath,
    },
  });
  const commands = await readFile(commandLog, "utf8").catch(() => "");
  await rm(sandbox, { force: true, recursive: true });
  return { commands, result };
}

test("scheduled pipeline applies the exact batch generated by its review run", async () => {
  const batchPath = "/tmp/runtime/reports/llm-learning-review-batches/run-123.json";
  const { commands, result } = await runPipeline({
    generated_batch: true,
    batch_id: `sha256:${"a".repeat(64)}`,
    batch_path: batchPath,
  });

  assert.equal(result.status, 0, result.stderr);
  assert.match(commands, /quality review-learnings/);
  assert.ok(commands.includes(`quality apply-learning-review --batch ${batchPath}`));
  assert.doesNotMatch(commands, /quality apply-learning-review\s*$/m);
});

test("scheduled pipeline does not apply when review generates no batch", async () => {
  const { commands, result } = await runPipeline({
    generated_batch: false,
    batch_id: null,
    batch_path: null,
    skipped: true,
    skip_reason: "llm_usd_budget_exhausted",
  });

  assert.equal(result.status, 0, result.stderr);
  assert.match(commands, /quality review-learnings/);
  assert.doesNotMatch(commands, /quality apply-learning-review/);
  assert.match(result.stdout, /no batch generated; skipping apply-learning-review/);
});

test("scheduled pipeline stops on review failure without applying stale output", async () => {
  const { commands, result } = await runPipeline(
    {
      generated_batch: true,
      batch_path: "/tmp/stale-batch.json",
    },
    { reviewExitCode: 17 },
  );

  assert.equal(result.status, 17);
  assert.match(commands, /quality review-learnings/);
  assert.doesNotMatch(commands, /quality apply-learning-review/);
});

test("scheduled pipeline skips review and apply when provider credentials are absent", async () => {
  const { commands, result } = await runPipeline({}, { apiKey: false });

  assert.equal(result.status, 0, result.stderr);
  assert.doesNotMatch(commands, /quality review-learnings/);
  assert.doesNotMatch(commands, /quality apply-learning-review/);
});
